@startuml

class Main {
  + Main():
  + main(String[]): void
}
class CompleteBinaryTree {
  + CompleteBinaryTree(String):
  + CompleteBinaryTree(Integer[]):
  - isMaxHeap(TreeNode, int): boolean
  + preorder(): void
  - inorderList(TreeNode, ArrayList<Integer>): void
  - preorder(TreeNode, int): void
  - isBinarySearchTree(TreeNode, Integer, Integer): boolean
  # makeNode(Integer[], int): TreeNode
  + inorderList(): ArrayList<Integer>
   maxHeap: boolean
   binarySearchTree: boolean
}

class InvalidTreeException {
  + InvalidTreeException(String):
}

class TreeNode {
  + TreeNode(Integer):
}

TreeNode              +-[#820000,plain]-  CompleteBinaryTree
@enduml
